app/profiles/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, DateField, IntegerField, FileField, TextAreaField, DateTimeField
from wtforms.fields.html5 import DateTimeLocalField
from wtforms.validators import DataRequired, Length

class AddRecordForm(FlaskForm):
    species = StringField('Species', [DataRequired(), Length(max=255)])
    datePlanted = DateField('Date Planted', [DataRequired()], format='%Y-%m-%d')
    numberOfTrees = IntegerField('Number of Trees', [DataRequired()])
    imageUrl = FileField('Upload Images', [Length(max=255)])
    location = StringField('Location', [DataRequired(), Length(max=255)])


class CreateEventForm(FlaskForm):
    title = StringField('Event Title', [DataRequired(), Length(max=255)])
    description = TextAreaField('Event Description', [DataRequired()])
    imageUrl = FileField('Upload Image', [Length(max=255)])
    startDateTime = DateTimeLocalField('Start Date and Time', [DataRequired()])
    endDateTime = DateTimeLocalField('End Date and Time', [DataRequired()])
    venue = StringField('Venue', [DataRequired(), Length(max=255)])
    organizer = StringField('Organizer', [Length(max=128)])

app/profiles/__init__.py
from flask import Blueprint, current_app

profiles = Blueprint('profiles', __name__, url_prefix = '/profiles')
from . import views, errors

@profiles.app_context_processor
def global_variables():
    """
    Provides global variables that can be accessed directly within templates
    belonging to the 'profiles' blueprint.

    Returns:
        dict: A dictionary containing global variables to be injected into 
        templates.
    """
    return dict(app_name = current_app.config['ORGANIZATION_NAME'])

app/profiles/views.py
import os
import flask
import glob
from flask_login import login_required, current_user
from werkzeug.utils import secure_filename
from sqlalchemy import func, or_
from geopy.geocoders import ArcGIS
from datetime import timedelta, datetime

from . import profiles
from .. import db
from .forms import AddRecordForm, CreateEventForm
from ..models import User


@profiles.route('/dashboard', methods = ["GET"])
def dashboard():
    return flask.render_template("profiles/dashboard.html")


@profiles.route('/add_record', methods = ["GET"])
def add_record():
    form = AddRecordForm()
    return flask.render_template("profiles/add_record.html", form = form)


@profiles.route('/all_records', methods = ["GET"])
def all_records():
    return flask.render_template("profiles/all_records.html")


@profiles.route('/other_events', methods = ["GET"])
def other_records():
    return flask.render_template("profiles/other_events.html")


@profiles.route("/create_event", methods = ["GET"])
def create_event():
    form = CreateEventForm()
    return flask.render_template("profiles/create_event.html", form = form)

app/templates/profiles/add_record.html
{% extends "base.html" %}
{% block title %}
Add Tree Planting Record
{% endblock %}

{% block page_content %}
<style>
.alert {
	background-color: #f3f4f6;
	border-left: 4px solid #e53e3e;
}
</style>
<div class="w-96 mx-auto bg-white p-6 rounded shadow-lg mt-10 mb-10">
	<h1 class="text-2xl font-bold mb-6 text-center">Add Tree Planting Record</h1>
	<!-- Alert for displaying messages -->
	<div id="alertMessage" class="hidden alert p-3 mb-6"></div>

	<form id="record-form" method="POST" action="/api/v1/add_record">
		{{ form.hidden_tag() }}
		<div class="mb-4">
			{{ form.species.label }}
			{{ form.species(class="w-full border border-gray-300 p-2", required=true) }}
		</div>
		<div class="mb-4">
			{{ form.datePlanted.label }}
			{{ form.datePlanted(class="w-full border border-gray-300 p-2", required=true) }}
		</div>
		<div class="mb-4">
			{{ form.numberOfTrees.label }}
			{{ form.numberOfTrees(class="w-full border border-gray-300 p-2", required=true) }}
		</div>
		<div class="mb-4">
			{{ form.imageUrl.label }}
			{{ form.imageUrl(class="w-full border border-gray-300 p-2") }}
		</div>
		<div class="mb-4">
			{{ form.location.label }}
			{{ form.location(class="w-full border border-gray-300 p-2", required=true) }}
		</div>
		<button type="submit" class="w-full bg-blue-500 text-white p-2 rounded hover:bg-blue-600">Add Record</button>
	</form>
</div>
<script src = "{{ url_for('static', filename = 'js/profiles/add_record.js') }}"></script>
{% endblock %}

app/templates/profiles/all_records.html
{% extends "base.html" %}
{% block title %}
All Records
{% endblock %}

{% block page_content %}
<script src = "{{ url_for('static', filename = 'js/profiles/all_records.js') }}"></script>
{% endblock %}

app/templates/profiles/attended_events.html
{% extends "base.html" %}
{% block title %}
Attended Events
{% endblock %}

{% block page_content %}
<script src = "{{ url_for('static', filename = 'js/profiles/attended_events.js') }}"></script>
{% endblock %}

app/templates/profiles/booked_events.html
{% extends "base.html" %}
{% block title %}
Booked Events
{% endblock %}

{% block page_content %}
<script src = "{{ url_for('static', filename = 'js/profiles/booked_events.js') }}"></script>
{% endblock %}

app/templates/profiles/create_event.html
{% extends "base.html" %}
{% block title %}
Event Registration
{% endblock %}

{% block page_content %}
<style>
.alert {
	background-color: #f3f4f6;
	border-left: 4px solid #e53e3e;
}
</style>
<div class="w-96 mx-auto bg-white p-6 rounded shadow-lg mt-10 mb-10">
	<h1 class="text-2xl font-bold mb-6 text-center">Event Registration</h1>
	<!-- Alert for displaying messages -->
	<div id="alertMessage" class="hidden alert p-3 mb-6"></div>

	<form id="event-registration-form" method="POST" action="/api/v1/create_event">
		{{ form.hidden_tag() }}
		<div class="mb-4">
			<label for="title" class="block text-gray-700">Event Title:</label>
			{{ form.title(class="w-full border border-gray-300 p-2", required=true) }}
		</div>
		<div class="mb-4">
			<label for="description" class="block text-gray-700">Event Description:</label>
			{{ form.description(class="w-full border border-gray-300 p-2", required=true) }}
		</div>
		<div class="mb-4">
			<label for="imageUrl" class="block text-gray-700">Image URL:</label>
			{{ form.imageUrl(class="w-full border border-gray-300 p-2") }}
		</div>
		<div class="mb-4">
			<label for="startDateTime" class="block text-gray-700">Start Date and Time:</label>
			{{ form.startDateTime(class="w-full border border-gray-300 p-2", required=true) }}
		</div>
		<div class="mb-4">
			<label for="endDateTime" class="block text-gray-700">End Date and Time:</label>
			{{ form.endDateTime(class="w-full border border-gray-300 p-2", required=true) }}
		</div>
		<div class="mb-4">
			<label for="venue" class="block text-gray-700">Venue:</label>
			{{ form.venue(class="w-full border border-gray-300 p-2", required=true) }}
		</div>
		<div class="mb-4">
			<label for="organizer" class="block text-gray-700">Organizer:</label>
			{{ form.organizer(class="w-full border border-gray-300 p-2") }}
		</div>
		<button type="submit" class="w-full bg-blue-500 text-white p-2 rounded hover:bg-blue-600">Register Event</button>
	</form>
</div>
<script src = "{{ url_for('static', filename = 'js/profiles/schedule_event.js') }}"></script>
{% endblock %}

app/templates/profiles/dashboard.html
{% extends "base.html" %}
{% block title %}
Dashboard
{% endblock %}

{% block page_content %}
<p><a href = "{{ url_for('profiles.add_record') }}">Add Record</a></p>
<p><a href = "{{ url_for('profiles.all_records', own = 1) }}">View Records</a></p>
<p><a href = "{{ url_for('profiles.create_event') }}">Create New Event</a></p>
<p><a href = "{{ url_for('profiles.add_record') }}">View All Records</a></p>
<p><a href = "{{ url_for('profiles.add_record') }}">View Scheduled Events</a></p>
<p><a href = "{{ url_for('profiles.add_record') }}">View All Events</a></p>
<p><a href = "{{ url_for('profiles.add_record') }}">View Attended Events</a></p>
<p><a href = "{{ url_for('profiles.add_record') }}">View Booked Events</a></p>
<p><a href = "{{ url_for('profiles.add_record') }}">Add Record</a></p>
<script src = "{{ url_for('static', filename = 'js/profiles/login_user.js') }}"></script>
{% endblock %}

app/templates/profiles/other_events.html
{% extends "base.html" %}
{% block title %}
Available Events
{% endblock %}

{% block page_content %}
<div class="bg-gray-100 p-6">
    <h1 class="text-2xl font-semibold mb-4">Available Events</h1>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6" id="event-container">
        <!-- Event cards will be dynamically added here using JavaScript -->
    </div>
</div>
<script src="{{ url_for('static', filename='js/profiles/all_events.js') }}"></script>
{% endblock %}

app/templates/profiles/schedule_event.html
{% extends "base.html" %}
{% block title %}
Dashboard
{% endblock %}

{% block page_content %}
<script src = "{{ url_for('static', filename = 'js/authentication/login_user.js') }}"></script>
{% endblock %}

app/templates/profiles/scheduled_events.html
{% extends "base.html" %}
{% block title %}
Dashboard
{% endblock %}

{% block page_content %}
<script src = "{{ url_for('static', filename = 'js/profiles/login_user.js') }}"></script>
{% endblock %}